execute pathogen#infect()

set laststatus=2
set showtabline=2
set noshowmode

set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4

map <F2> :NERDTreeToggle<CR>
set pastetoggle=<F4>
nmap <F3> :set invnumber<CR>

set termguicolors
colorscheme gotham

" Display airline, with the gotham theme.
set laststatus=2
let g:airline_theme='gotham'
let g:airline#extensions#tabline#enabled = 1

" Make NERDTree show hidden files.
let NERDTreeShowHidden=1

